version: '3.7'
services:
  postgres:
    container_name: postgres:latest
    ports:
      - '5432:5432'
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      # these are only used for development, so doesn't matter if its here
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
volumes:
  postgres:
